"""Emit the trained quad detector as a self-contained JS file for the worker.

The recognition worker is a *classic* Web Worker — it needs `importScripts` for
OpenCV — so it cannot import an ES-module ML runtime, and pulling one in for a
0.5M-parameter model would be absurd anyway. Four strided convolutions and two
dense layers are about sixty lines of plain JS.

BatchNorm is folded into the preceding convolution, so inference is
conv -> bias -> relu with no normalisation layer at runtime:

    W' = W * gamma / sqrt(var + eps)
    b' = (b - mean) * gamma / sqrt(var + eps) + beta

Weights ship as base64 Float32 rather than JSON numbers: 4 bytes per weight
instead of ~12 characters.

    python3 scripts/export_detector_js.py [in.pt] [out.js]
"""
import base64, json, os, sys
import numpy as np
import torch

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from train_detector import Detector, SIZE, ASPECT

SRC = sys.argv[1] if len(sys.argv) > 1 else "/tmp/detector/detector.pt"
DST = sys.argv[2] if len(sys.argv) > 2 else "public/carddata/detector.js"


def fold(conv, bn):
    """Fold BatchNorm into the conv that precedes it."""
    w = conv.weight.detach().numpy().astype(np.float32)
    b = (conv.bias.detach().numpy() if conv.bias is not None
         else np.zeros(w.shape[0], np.float32)).astype(np.float32)
    g = bn.weight.detach().numpy().astype(np.float32)
    beta = bn.bias.detach().numpy().astype(np.float32)
    mean = bn.running_mean.detach().numpy().astype(np.float32)
    var = bn.running_var.detach().numpy().astype(np.float32)
    scale = g / np.sqrt(var + bn.eps)
    return w * scale[:, None, None, None], (b - mean) * scale + beta


def b64(a):
    return base64.b64encode(np.ascontiguousarray(a, np.float32).tobytes()).decode("ascii")


def main():
    ckpt = torch.load(SRC, map_location="cpu", weights_only=True)
    model = Detector()
    model.load_state_dict(ckpt["state"])
    model.eval()

    layers = []
    for blk in model.features:
        if isinstance(blk, torch.nn.Sequential):
            w, b = fold(blk[0], blk[1])
            layers.append({"w": w, "b": b, "stride": blk[0].stride[0], "pad": blk[0].padding[0]})
    fc1, fc2 = model.head[1], model.head[3]

    # Verify the exported numbers reproduce torch before anything ships, so an
    # integration failure can only be model quality and never a silent
    # numerical mismatch.
    rng = np.random.default_rng(0)
    probe = rng.random((1, 3, SIZE, SIZE), dtype=np.float32)
    with torch.no_grad():
        want = model(torch.from_numpy(probe)).numpy()[0]

    x = probe[0]
    for L in layers:
        w, b, s, p = L["w"], L["b"], L["stride"], L["pad"]
        cin, hin, win = x.shape
        cout = w.shape[0]
        hout, wout = (hin + 2 * p - 3) // s + 1, (win + 2 * p - 3) // s + 1
        xp = np.pad(x, ((0, 0), (p, p), (p, p)))
        out = np.zeros((cout, hout, wout), np.float32)
        for ky in range(3):
            for kx in range(3):
                patch = xp[:, ky:ky + hout * s:s, kx:kx + wout * s:s]
                out += np.tensordot(w[:, :, ky, kx], patch, axes=([1], [0]))
        x = np.maximum(out + b[:, None, None], 0)
    c, h, _ = x.shape
    step = h // 4
    pooled = x.reshape(c, 4, step, 4, step).mean(axis=(2, 4)).reshape(-1)
    hid = np.maximum(pooled @ fc1.weight.detach().numpy().T + fc1.bias.detach().numpy(), 0)
    got = hid @ fc2.weight.detach().numpy().T + fc2.bias.detach().numpy()

    err = float(np.abs(got - want).max())
    print(f"numpy-vs-torch max abs error: {err:.2e}")
    if err > 1e-3:
        raise SystemExit("export path does not reproduce torch; refusing to write")

    payload = {
        "size": SIZE, "aspect": ASPECT,
        "layers": [{"shape": list(L["w"].shape), "stride": L["stride"], "pad": L["pad"],
                    "w": b64(L["w"]), "b": b64(L["b"])} for L in layers],
        "fc1": {"shape": list(fc1.weight.shape), "w": b64(fc1.weight.detach().numpy()),
                "b": b64(fc1.bias.detach().numpy())},
        "fc2": {"shape": list(fc2.weight.shape), "w": b64(fc2.weight.detach().numpy()),
                "b": b64(fc2.bias.detach().numpy())},
        "probe": {"in": b64(probe), "out": b64(want)},
    }

    js = """// GENERATED by scripts/export_detector_js.py — do not edit.
//
// Card-quad detector for the recognition worker. Predicts where the clicked
// card is, so the click-local isolation sweep — the single largest cost in the
// pipeline — only has to run when this abstains.
//
// Plain JS on purpose: the worker is a classic Worker (it needs importScripts
// for OpenCV) and cannot import an ML runtime. BatchNorm is folded into each
// convolution at export, so this is conv -> bias -> relu throughout.
//
// self.__SNAP_DETECTOR.predict(rgbFloat32, size) -> {cx, cy, h, angleDeg}
// with every value normalised to the input crop.
(function () {
  var M = %s;

  function unb64(s) {
    var bin = atob(s), n = bin.length, u8 = new Uint8Array(n);
    for (var i = 0; i < n; i++) u8[i] = bin.charCodeAt(i);
    return new Float32Array(u8.buffer);
  }
  for (var i = 0; i < M.layers.length; i++) {
    M.layers[i].W = unb64(M.layers[i].w);
    M.layers[i].B = unb64(M.layers[i].b);
  }
  M.fc1.W = unb64(M.fc1.w); M.fc1.B = unb64(M.fc1.b);
  M.fc2.W = unb64(M.fc2.w); M.fc2.B = unb64(M.fc2.b);

  // x: Float32Array laid out [channel][y][x]
  function conv(x, cin, hin, win, L) {
    var cout = L.shape[0], k = 3, s = L.stride, p = L.pad;
    var hout = ((hin + 2 * p - k) / s | 0) + 1, wout = ((win + 2 * p - k) / s | 0) + 1;
    var out = new Float32Array(cout * hout * wout);
    var W = L.W, B = L.B;
    for (var oc = 0; oc < cout; oc++) {
      var obase = oc * hout * wout, bias = B[oc];
      for (var oy = 0; oy < hout; oy++) {
        for (var ox = 0; ox < wout; ox++) out[obase + oy * wout + ox] = bias;
      }
      for (var ic = 0; ic < cin; ic++) {
        var wbase = ((oc * cin + ic) * k) * k, ibase = ic * hin * win;
        for (var ky = 0; ky < k; ky++) {
          for (var kx = 0; kx < k; kx++) {
            var wv = W[wbase + ky * k + kx];
            if (wv === 0) continue;
            for (var oy2 = 0; oy2 < hout; oy2++) {
              var iy = oy2 * s + ky - p;
              if (iy < 0 || iy >= hin) continue;
              var orow = obase + oy2 * wout, irow = ibase + iy * win;
              for (var ox2 = 0; ox2 < wout; ox2++) {
                var ix = ox2 * s + kx - p;
                if (ix < 0 || ix >= win) continue;
                out[orow + ox2] += wv * x[irow + ix];
              }
            }
          }
        }
      }
    }
    for (var j = 0; j < out.length; j++) if (out[j] < 0) out[j] = 0;
    return { x: out, c: cout, h: hout, w: wout };
  }

  function predict(rgb, size) {
    var cur = { x: rgb, c: 3, h: size, w: size };
    for (var i = 0; i < M.layers.length; i++) {
      cur = conv(cur.x, cur.c, cur.h, cur.w, M.layers[i]);
    }
    // adaptive average pool to 4x4
    var step = cur.h / 4, pooled = new Float32Array(cur.c * 16);
    for (var c = 0; c < cur.c; c++) {
      for (var py = 0; py < 4; py++) {
        for (var px = 0; px < 4; px++) {
          var sum = 0;
          for (var yy = 0; yy < step; yy++) {
            for (var xx = 0; xx < step; xx++) {
              sum += cur.x[c * cur.h * cur.w + (py * step + yy) * cur.w + (px * step + xx)];
            }
          }
          pooled[c * 16 + py * 4 + px] = sum / (step * step);
        }
      }
    }
    var h1 = new Float32Array(M.fc1.shape[0]);
    for (var o = 0; o < M.fc1.shape[0]; o++) {
      var acc = M.fc1.B[o], row = o * M.fc1.shape[1];
      for (var k2 = 0; k2 < M.fc1.shape[1]; k2++) acc += M.fc1.W[row + k2] * pooled[k2];
      h1[o] = acc > 0 ? acc : 0;
    }
    var out = new Float32Array(M.fc2.shape[0]);
    for (var o2 = 0; o2 < M.fc2.shape[0]; o2++) {
      var acc2 = M.fc2.B[o2], row2 = o2 * M.fc2.shape[1];
      for (var k3 = 0; k3 < M.fc2.shape[1]; k3++) acc2 += M.fc2.W[row2 + k3] * h1[k3];
      out[o2] = acc2;
    }
    // orientation is doubled in the target, so halve the recovered angle
    return { cx: out[0], cy: out[1], h: out[2],
             angleDeg: Math.atan2(out[4], out[3]) * 90 / Math.PI };
  }

  self.__SNAP_DETECTOR = {
    size: M.size, aspect: M.aspect, predict: predict,
    // Reproduces the fixed probe the exporter checked against torch, so a
    // broken port is detectable at load rather than as mysterious bad crops.
    selfTest: function () {
      var inp = unb64(M.probe.in), want = unb64(M.probe.out);
      var r = predict(inp, M.size);
      var got = [r.cx, r.cy, r.h];
      var err = Math.max(Math.abs(got[0] - want[0]), Math.abs(got[1] - want[1]),
                         Math.abs(got[2] - want[2]));
      return { ok: err < 1e-3, err: err };
    },
  };
})();
""" % json.dumps(payload)

    os.makedirs(os.path.dirname(DST), exist_ok=True)
    with open(DST, "w") as f:
        f.write(js)
    print(f"wrote {DST}  ({os.path.getsize(DST)/1024:.0f} KB)")


if __name__ == "__main__":
    main()
